# %% [markdown]
# # Notebook 6 — Q-Measure Multi-Factor Short Rate AEMM (Chapter 3.2)
#
# This notebook implements the **Short Rate Autoencoder Market Model** from §3.2:
#
# 1. **Classical G(K)++ model review** (Eq. 18-24)
# 2. **Hierarchical decomposition** of VAE-generated forward rates (Eq. 26, Fig. 18)
# 3. **Non-linear drift calibration** μₖ(t, x₁...xₖ) from VAE decoder (Eq. 25)
# 4. **Deterministic shift φ(t)** to match initial yield curve
# 5. **Short rate AEMM simulation** and comparison with G2++
#
# Key insight: In short rate models, the volatility basis is replaced by a 
# **non-linear drift** derived from VAE decoder. The rate of exponential decay 
# in forward rate models plays the same role as mean reversion speed here.

# %% [markdown]
# ## 0 — Imports

# %%
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import warnings
warnings.filterwarnings("ignore")

import torch
import torch.nn as nn
from scipy.optimize import minimize
from typing import Dict, Tuple, List, Optional
from pathlib import Path

Path("figs").mkdir(parents=True, exist_ok=True)

plt.rcParams.update({
    "figure.figsize": (14, 6),
    "axes.grid": True,
    "grid.alpha": 0.3,
    "font.size": 11,
})

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# %% [markdown]
# ## 1 — Load data & VAE

# %%
with open("clean_swap_data.pkl", "rb") as f:
    data = pickle.load(f)
with open("vae_results.pkl", "rb") as f:
    vae_data = pickle.load(f)

swap_aligned = data["swap_aligned"]
TARGET_TENORS = data["target_tenors"]
TENORS = np.array(TARGET_TENORS, dtype=float)

cfg = vae_data["config"]
S_MIN, S_MAX = float(cfg["S_MIN"]), float(cfg["S_MAX"])
BP_PER_UNIT = float(cfg["bp_per_unit"])
CURRENCIES = cfg["currencies"]

def normalize_rates(r):
    return np.clip((r - S_MIN) / (S_MAX - S_MIN), 0, 1)
def denormalize_rates(x):
    return x * (S_MAX - S_MIN) + S_MIN

# %%
class VAE(nn.Module):
    def __init__(self, input_dim=7, latent_dim=2, hidden_dim=4, multi_currency=False):
        super().__init__()
        self.input_dim = input_dim
        self.latent_dim = latent_dim
        if not multi_currency:
            self.encoder = nn.Sequential(
                nn.Linear(input_dim, hidden_dim), nn.Tanh(),
                nn.Linear(hidden_dim, 2 * latent_dim))
            self.decoder = nn.Sequential(
                nn.Linear(latent_dim, hidden_dim), nn.Tanh(),
                nn.Linear(hidden_dim, input_dim), nn.Sigmoid())
        else:
            self.encoder = nn.Sequential(
                nn.Linear(input_dim, input_dim), nn.Tanh(),
                nn.Linear(input_dim, 2 * latent_dim))
            self.decoder = nn.Sequential(
                nn.Linear(latent_dim, hidden_dim), nn.Tanh(),
                nn.Linear(hidden_dim, input_dim), nn.Tanh(),
                nn.Linear(input_dim, input_dim), nn.Sigmoid())

    def encode(self, x):
        h = self.encoder(x)
        return h[:, :self.latent_dim], h[:, self.latent_dim:]
    def decode(self, z):
        return self.decoder(z)
    def forward(self, x):
        mu, logvar = self.encode(x)
        return self.decode(mu), mu, logvar
    def get_latent(self, x):
        self.eval()
        with torch.no_grad():
            mu, _ = self.encode(x.to(device))
        return mu.cpu().numpy()

multi_vae = VAE(7, 2, 4, multi_currency=True).to(device)
multi_vae.load_state_dict(torch.load("multi_vae_weights.pt", map_location=device))
multi_vae.eval()
print("Multi-currency VAE loaded")

# %% [markdown]
# ## 2 — Bootstrap utilities (from NB5)

# %%
def swap_to_discount(swap_rates, tenors):
    max_tenor = int(tenors[-1])
    annual_tenors = np.arange(1, max_tenor + 1, dtype=float)
    swap_annual = np.interp(annual_tenors, tenors, swap_rates)
    df = np.zeros(max_tenor)
    for i in range(max_tenor):
        s = swap_annual[i]
        df[i] = (1.0 - s * np.sum(df[:i])) / (1.0 + s) if i > 0 else 1.0 / (1.0 + s)
    return np.interp(tenors, annual_tenors, df)

def discount_to_zero(df, tenors):
    return -np.log(np.maximum(df, 1e-10)) / tenors

def zero_to_forward(zero_rates, tenors):
    tau_R = tenors * zero_rates
    return np.gradient(tau_R, tenors)

def swap_to_forward(swap_rates, tenors):
    df = swap_to_discount(swap_rates, tenors)
    zr = discount_to_zero(df, tenors)
    return zero_to_forward(zr, tenors)

# %% [markdown]
# ---
# ## 3 — Classical G(2)++ Model (§3.2.1)
#
# The G(2)++ model (Eq. 18-19):
#
# $$r(t) = \varphi(t) + x_1(t) + x_2(t)$$
# $$dx_k = -a_k x_k dt + \sigma_k dw_k, \quad k=1,2$$
#
# The forward rate generated by this model:
# $$f(t, T) = f(0, T) + \sum_k x_k(t) e^{-a_k(T-t)} + f_{conv}(t, T)$$
#
# where $f_{conv}$ is the convexity adjustment (O(σ²)).

# %%
class G2PlusPlus:
    """
    Classical G(2)++ short rate model.
    
    Parameters: a1, a2 (mean reversion), sigma1, sigma2 (vol), rho (correlation)
    """
    
    def __init__(self, a1: float = 0.5, a2: float = 0.05,
                 sigma1: float = 0.01, sigma2: float = 0.005,
                 rho: float = -0.7):
        self.a1 = a1
        self.a2 = a2
        self.sigma1 = sigma1
        self.sigma2 = sigma2
        self.rho = rho
    
    def forward_rate_shift(self, x: np.ndarray, T: np.ndarray, t: float = 0.0) -> np.ndarray:
        """
        Shift in forward rate due to state variables x = (x1, x2):
        Δf(T) = x1 * exp(-a1*(T-t)) + x2 * exp(-a2*(T-t))
        """
        tau = T - t
        return x[0] * np.exp(-self.a1 * tau) + x[1] * np.exp(-self.a2 * tau)
    
    def convexity_adjustment(self, T: np.ndarray, t: float = 0.0) -> np.ndarray:
        """O(σ²) convexity drift in forward rates."""
        tau = T - t
        s1, s2 = self.sigma1, self.sigma2
        a1, a2 = self.a1, self.a2
        
        # Simplified convexity for G2++
        term1 = (s1**2 / (2 * a1**2)) * (1 - np.exp(-a1 * tau))**2
        term2 = (s2**2 / (2 * a2**2)) * (1 - np.exp(-a2 * tau))**2
        term3 = (self.rho * s1 * s2 / (a1 * a2)) * (1 - np.exp(-a1 * tau)) * (1 - np.exp(-a2 * tau))
        
        return term1 + term2 + term3
    
    def simulate(self, f0: np.ndarray, tenors: np.ndarray,
                 n_steps: int = 252, dt: float = 1/252,
                 n_paths: int = 100, seed: int = 42) -> np.ndarray:
        """
        Simulate G2++ paths.
        Returns swap_paths: (n_paths, n_steps+1, N_tenors)
        """
        np.random.seed(seed)
        N = len(tenors)
        K = 2
        
        # Cholesky for correlated shocks
        L = np.linalg.cholesky(np.array([
            [1.0, self.rho],
            [self.rho, 1.0]
        ]))
        
        x_paths = np.zeros((n_paths, n_steps + 1, K))
        fwd_paths = np.zeros((n_paths, n_steps + 1, N))
        fwd_paths[:, 0, :] = f0
        
        sigmas = np.array([self.sigma1, self.sigma2])
        a_vec = np.array([self.a1, self.a2])
        
        for p in range(n_paths):
            x = np.zeros(K)
            for t in range(n_steps):
                # Correlated shocks
                xi = L @ np.random.randn(K)
                
                # Euler step
                for k in range(K):
                    x[k] += -a_vec[k] * x[k] * dt + sigmas[k] * np.sqrt(dt) * xi[k]
                
                x_paths[p, t+1] = x.copy()
                
                # Forward rate shift
                delta_f = self.forward_rate_shift(x, tenors)
                conv = self.convexity_adjustment(tenors, t=0)
                fwd_paths[p, t+1] = f0 + delta_f + conv
        
        return fwd_paths, x_paths

# %% [markdown]
# ---
# ## 4 — Hierarchical Decomposition of VAE Forward Rates (Eq. 26)
#
# We decompose the VAE-generated forward rate into components:
#
# $$\hat{f}(\tau, z) = \sum_{k=1}^{K} \hat{f}_k(\tau, z_1 \ldots z_k)$$
#
# where each component depends only on z₁...zₖ (not higher dimensions).
# This provides the calibration target for each state variable's drift.

# %%
def decode_forward_at_z(model: VAE, z: np.ndarray, tenors: np.ndarray) -> np.ndarray:
    """Decode z → swap rates → forward rates."""
    model.eval()
    z_t = torch.from_numpy(z.astype(np.float32)).unsqueeze(0).to(device)
    with torch.no_grad():
        s_norm = model.decode(z_t).cpu().numpy()[0]
    s = denormalize_rates(s_norm)
    return swap_to_forward(s, tenors)


def hierarchical_decomposition(
    model: VAE,
    z_grid: np.ndarray,
    tenors: np.ndarray,
) -> Dict[str, np.ndarray]:
    """
    Hierarchical decomposition of VAE-generated forward rates (Eq. 26).
    
    For K=2:
    - f̂₁(τ, z₁) = f̂(τ, z₁, z₂=0) - f̂(τ, 0, 0)
    - f̂₂(τ, z₁, z₂) = f̂(τ, z₁, z₂) - f̂(τ, z₁, 0)
    
    Parameters
    ----------
    model : trained VAE
    z_grid : (n_points, K) grid of latent points
    tenors : maturity grid
    
    Returns
    -------
    dict with f_total, f_component_1, f_component_2 arrays
    """
    K = z_grid.shape[1]
    n_pts = z_grid.shape[0]
    N = len(tenors)
    
    # Reference: f at z = 0
    z_zero = np.zeros(K)
    f_zero = decode_forward_at_z(model, z_zero, tenors)
    
    f_total = np.zeros((n_pts, N))
    f_comp = {k: np.zeros((n_pts, N)) for k in range(K)}
    
    for i in range(n_pts):
        z = z_grid[i]
        
        # Full forward rate
        f_full = decode_forward_at_z(model, z, tenors)
        f_total[i] = f_full - f_zero  # shift relative to origin
        
        # Component 1: only z₁ active (z₂=...=0)
        z_partial = np.zeros(K)
        z_partial[0] = z[0]
        f_partial_1 = decode_forward_at_z(model, z_partial, tenors)
        f_comp[0][i] = f_partial_1 - f_zero
        
        # Component 2: z₂ contribution = f(z₁,z₂) - f(z₁,0)
        if K >= 2:
            f_comp[1][i] = f_total[i] - f_comp[0][i]
    
    return {
        "f_total": f_total,
        "f_zero": f_zero,
        "f_components": f_comp,
        "z_grid": z_grid,
    }

# %% [markdown]
# ### 4.1 — Compute hierarchical decomposition (Fig. 18)

# %%
# Create grid spanning the latent space for USD
ccy_demo = "USD"
df_demo = swap_aligned[ccy_demo]
rates_norm = normalize_rates(df_demo.values.astype(np.float32))
z_ccy = multi_vae.get_latent(torch.from_numpy(rates_norm))

# Grid over 2σ range
z_mean = z_ccy.mean(axis=0)
z_std = z_ccy.std(axis=0)

n_grid = 15
z1_range = np.linspace(z_mean[0] - 2*z_std[0], z_mean[0] + 2*z_std[0], n_grid)
z2_range = np.linspace(z_mean[1] - 2*z_std[1], z_mean[1] + 2*z_std[1], n_grid)

# Create grid with z₂ at its mean (for component 1 visualisation)
z_grid_z1 = np.column_stack([z1_range, np.full(n_grid, z_mean[1])])
z_grid_z2 = np.column_stack([np.full(n_grid, z_mean[0]), z2_range])

# Full 2D grid
z1_mesh, z2_mesh = np.meshgrid(z1_range, z2_range)
z_grid_full = np.column_stack([z1_mesh.ravel(), z2_mesh.ravel()])

print(f"Computing hierarchical decomposition for {ccy_demo}...")
decomp = hierarchical_decomposition(multi_vae, z_grid_full, TENORS)
print("Done.")

# %% [markdown]
# ### 4.2 — Visualise decomposition (cf. Fig. 18a/18b)

# %%
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# (a) Component 1: f̂₁(τ, z₁) — varies with z₁
ax = axes[0]
decomp_z1 = hierarchical_decomposition(multi_vae, z_grid_z1, TENORS)
for i in range(n_grid):
    color_val = (z1_range[i] - z1_range[0]) / (z1_range[-1] - z1_range[0])
    ax.plot(TENORS, 100 * decomp_z1["f_components"][0][i],
            color=plt.cm.coolwarm(color_val), lw=1.5, alpha=0.8)
ax.set_xlabel("Maturity τ (years)")
ax.set_ylabel("Forward rate shift (pp)")
ax.set_title("(a) f̂₁(τ, z₁) — Factor 1 contribution\n(varying z₁, z₂ fixed)")
ax.axhline(0, color="black", lw=0.5, ls="--")

# (b) Component 2: f̂₂(τ, z₁, z₂) — varies with z₂
ax = axes[1]
decomp_z2 = hierarchical_decomposition(multi_vae, z_grid_z2, TENORS)
for i in range(n_grid):
    color_val = (z2_range[i] - z2_range[0]) / (z2_range[-1] - z2_range[0])
    ax.plot(TENORS, 100 * decomp_z2["f_components"][1][i],
            color=plt.cm.PiYG(color_val), lw=1.5, alpha=0.8)
ax.set_xlabel("Maturity τ (years)")
ax.set_ylabel("Forward rate shift (pp)")
ax.set_title("(b) f̂₂(τ, z₁, z₂) — Factor 2 contribution\n(z₁ fixed, varying z₂)")
ax.axhline(0, color="black", lw=0.5, ls="--")

# (c) Total = component 1 + component 2
ax = axes[2]
# Show a few full curves
indices = np.random.choice(len(z_grid_full), size=min(40, len(z_grid_full)), replace=False)
for idx in indices:
    ax.plot(TENORS, 100 * decomp["f_total"][idx], alpha=0.3, lw=0.8, color="steelblue")
ax.set_xlabel("Maturity τ (years)")
ax.set_ylabel("Forward rate shift (pp)")
ax.set_title("(c) Total Δf̂(τ, z) = f̂₁ + f̂₂")
ax.axhline(0, color="black", lw=0.5, ls="--")

plt.suptitle(f"Hierarchical Decomposition — {ccy_demo} (cf. Fig. 18)", fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig("figs/fig_24_hierarchical_decomp.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ---
# ## 5 — Non-linear Drift Calibration (Eq. 25)
#
# The short rate AEMM replaces the linear mean reversion drift $-a_k x_k$ of G(K)++
# with a non-linear drift $\mu_k(t, x_1 \ldots x_k)$ calibrated to VAE-generated curves:
#
# $$r(t) = \varphi(t) + \sum_k x_k(t)$$
# $$dx_k = \mu_k(t, x_1 \ldots x_k) dt + \sigma_k(t) dw_k$$
#
# We calibrate μₖ by fitting to the VAE decoder's forward rate decomposition.

# %%
def calibrate_drift_time_homogeneous(
    model: VAE,
    z_data: np.ndarray,
    tenors: np.ndarray,
    sigma: np.ndarray,
    dt: float = 1/252,
) -> Dict[str, object]:
    """
    Calibrate time-homogeneous drift μₖ(x₁...xₖ) from VAE-generated curves.
    
    The drift at each point in latent space is estimated from:
    - The average forward rate change when z moves by a small amount
    - Scaled to match the model's mean reversion pattern
    
    This is a grid-based calibration that estimates drift on a 2D grid.
    
    Parameters
    ----------
    model : trained VAE
    z_data : (N, K) historical latent codes
    tenors : maturity grid
    sigma : (K,) volatility of each latent factor
    
    Returns
    -------
    dict with drift_grid, z_grid, etc.
    """
    K = z_data.shape[1]
    z_mean = z_data.mean(axis=0)
    z_std = z_data.std(axis=0)
    
    # Estimate drift from first differences of z (time-homogeneous assumption)
    dz = np.diff(z_data, axis=0)
    
    # Bin drift by current z position
    n_bins = 10
    z1_edges = np.linspace(z_mean[0] - 3*z_std[0], z_mean[0] + 3*z_std[0], n_bins + 1)
    z2_edges = np.linspace(z_mean[1] - 3*z_std[1], z_mean[1] + 3*z_std[1], n_bins + 1)
    
    drift_grid = np.full((n_bins, n_bins, K), np.nan)
    count_grid = np.zeros((n_bins, n_bins))
    
    for i in range(len(dz)):
        z_cur = z_data[i]
        i1 = np.searchsorted(z1_edges[1:], z_cur[0])
        i2 = np.searchsorted(z2_edges[1:], z_cur[1])
        if 0 <= i1 < n_bins and 0 <= i2 < n_bins:
            if np.isnan(drift_grid[i1, i2, 0]):
                drift_grid[i1, i2] = dz[i] / dt
            else:
                n = count_grid[i1, i2]
                drift_grid[i1, i2] = (drift_grid[i1, i2] * n + dz[i] / dt) / (n + 1)
            count_grid[i1, i2] += 1
    
    # Centers of bins
    z1_centers = 0.5 * (z1_edges[:-1] + z1_edges[1:])
    z2_centers = 0.5 * (z2_edges[:-1] + z2_edges[1:])
    
    return {
        "drift_grid": drift_grid,
        "count_grid": count_grid,
        "z1_centers": z1_centers,
        "z2_centers": z2_centers,
        "z1_edges": z1_edges,
        "z2_edges": z2_edges,
    }

# %% [markdown]
# ### 5.1 — Estimate drift field

# %%
# Get historical z sequence for USD
rates_norm = normalize_rates(swap_aligned[ccy_demo].values.astype(np.float32))
z_series = multi_vae.get_latent(torch.from_numpy(rates_norm))

# Historical vol
dz_daily = np.diff(z_series, axis=0)
vol_z = np.std(dz_daily, axis=0)
print(f"Daily vol in z-space: {vol_z}")

# Calibrate drift
drift_calib = calibrate_drift_time_homogeneous(
    multi_vae, z_series, TENORS, sigma=vol_z, dt=1/252
)

# %% [markdown]
# ### 5.2 — Visualise drift vector field

# %%
fig, axes = plt.subplots(1, 2, figsize=(18, 8))

# Quiver plot of drift
ax = axes[0]
ax.scatter(z_series[:, 0], z_series[:, 1], s=1, alpha=0.1, color="gray")

dg = drift_calib["drift_grid"]
cg = drift_calib["count_grid"]
z1c = drift_calib["z1_centers"]
z2c = drift_calib["z2_centers"]

for i in range(len(z1c)):
    for j in range(len(z2c)):
        if cg[i, j] > 5 and not np.any(np.isnan(dg[i, j])):
            # Scale drift for visibility
            ax.arrow(z1c[i], z2c[j],
                    dg[i, j, 0] * 0.01, dg[i, j, 1] * 0.01,
                    head_width=0.005, head_length=0.002,
                    fc="tab:red", ec="tab:red", alpha=0.7)

ax.set_xlabel("$z_1$")
ax.set_ylabel("$z_2$")
ax.set_title(f"(a) Estimated drift field — {ccy_demo}")

# Mean reversion illustration
ax = axes[1]
# Plot drift magnitude
for k, label in enumerate(["$\\mu_1$ (drift of $z_1$)", "$\\mu_2$ (drift of $z_2$)"]):
    # Average drift vs z_k
    drift_vs_zk = []
    zk_vals = []
    for i in range(len(z1c) if k == 0 else len(z2c)):
        if k == 0:
            mask = cg[i, :] > 3
            if mask.sum() > 0:
                avg_drift = np.nanmean(dg[i, mask, k])
                drift_vs_zk.append(avg_drift)
                zk_vals.append(z1c[i])
        else:
            mask = cg[:, i] > 3
            if mask.sum() > 0:
                avg_drift = np.nanmean(dg[mask, i, k])
                drift_vs_zk.append(avg_drift)
                zk_vals.append(z2c[i])
    
    if drift_vs_zk:
        ax.plot(zk_vals, drift_vs_zk, "o-", label=label, lw=2)

ax.axhline(0, color="black", lw=0.5, ls="--")
ax.set_xlabel("$z_k$")
ax.set_ylabel("Drift (per day)")
ax.set_title("(b) Mean drift vs latent factor value\n(evidence of mean reversion)")
ax.legend()

plt.suptitle(f"Short Rate AEMM: Non-linear Drift — {ccy_demo}", fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig("figs/fig_25_drift_field.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ---
# ## 6 — Deterministic Shift φ(t)
#
# The deterministic shift ensures the model matches the initial yield curve:
# $$\varphi(t) = f^{market}(0, t) - \hat{f}^{VAE}(t, z_0)$$
#
# where z₀ are the initial state variables.

# %%
# Compute φ(t) for the initial curve
z0 = z_series[-1]  # latest observation
f_vae = decode_forward_at_z(multi_vae, z0, TENORS)

# Market forward rates
swap_market = swap_aligned[ccy_demo].iloc[-1].values.astype(float)
f_market = swap_to_forward(swap_market, TENORS)

phi = f_market - f_vae

fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(TENORS, 100 * f_market, "ko-", label="Market forward", lw=2)
ax.plot(TENORS, 100 * f_vae, "s--", label="VAE-decoded forward", lw=2)
ax.plot(TENORS, 100 * phi, "^-", label="φ(t) = Market - VAE", lw=2)
ax.axhline(0, color="black", lw=0.5, ls="--")
ax.set_xlabel("Maturity (years)")
ax.set_ylabel("Rate (%)")
ax.set_title(f"Deterministic Shift φ(t) — {ccy_demo}")
ax.legend()
plt.tight_layout()
plt.savefig("figs/fig_26_phi_shift.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"Max |φ|: {np.max(np.abs(phi))*10000:.2f} bp")

# %% [markdown]
# ---
# ## 7 — Short Rate AEMM Simulation
#
# We simulate the short rate AEMM using:
# 1. z dynamics in latent space (with estimated drift and historical vol)
# 2. Decode z → forward rate curve at each step
# 3. Add deterministic shift φ(t)

# %%
def simulate_short_rate_aemm(
    model: VAE,
    z_init: np.ndarray,
    phi: np.ndarray,
    tenors: np.ndarray,
    vol_z: np.ndarray,
    drift_calib: dict,
    n_steps: int = 252,
    dt: float = 1/252,
    n_paths: int = 100,
    seed: int = 42,
) -> Dict[str, np.ndarray]:
    """
    Simulate Short Rate AEMM.
    
    Uses estimated mean-reverting drift in latent space + VAE decoder.
    """
    np.random.seed(seed)
    K = len(z_init)
    N = len(tenors)
    
    z_paths = np.zeros((n_paths, n_steps + 1, K))
    fwd_paths = np.zeros((n_paths, n_steps + 1, N))
    short_rates = np.zeros((n_paths, n_steps + 1))
    
    # Initial forward rates
    f0 = decode_forward_at_z(model, z_init, tenors)
    
    # Simple mean-reverting drift: μ(z) ≈ -a * (z - z_mean)
    z_mean = np.zeros(K)
    dg = drift_calib["drift_grid"]
    cg = drift_calib["count_grid"]
    # Estimate a from linear regression of drift on z
    z1c = drift_calib["z1_centers"]
    z2c = drift_calib["z2_centers"]
    
    # Rough mean reversion estimates
    a_est = np.zeros(K)
    z_target = np.zeros(K)
    for k in range(K):
        zk_vals, dk_vals = [], []
        if k == 0:
            for i in range(len(z1c)):
                mask = cg[i, :] > 3
                if mask.sum() > 0 and not np.all(np.isnan(dg[i, mask, k])):
                    dk_vals.append(np.nanmean(dg[i, mask, k]))
                    zk_vals.append(z1c[i])
        else:
            for j in range(len(z2c)):
                mask = cg[:, j] > 3
                if mask.sum() > 0 and not np.all(np.isnan(dg[mask, j, k])):
                    dk_vals.append(np.nanmean(dg[mask, j, k]))
                    zk_vals.append(z2c[j])
        
        if len(zk_vals) > 2:
            # Linear fit: drift = -a*(z - z_target)
            zk_arr = np.array(zk_vals)
            dk_arr = np.array(dk_vals)
            coeffs = np.polyfit(zk_arr, dk_arr, 1)
            a_est[k] = -coeffs[0] * dt  # convert to annualised
            z_target[k] = -coeffs[1] / coeffs[0] if abs(coeffs[0]) > 1e-10 else 0.0
    
    print(f"Estimated mean reversion: a = {a_est}")
    print(f"Estimated target: z* = {z_target}")
    
    for p in range(n_paths):
        z = z_init.copy()
        z_paths[p, 0] = z
        fwd_paths[p, 0] = f0 + phi
        short_rates[p, 0] = (f0 + phi)[0]  # approximate short rate from first forward
        
        for t in range(n_steps):
            # Drift: mean reversion
            drift = -a_est * (z - z_target)
            
            # Diffusion
            xi = np.random.randn(K)
            dz = drift * dt + vol_z * np.sqrt(dt) * xi
            z = z + dz
            
            # Decode to forward rates + shift
            f_vae = decode_forward_at_z(model, z, tenors)
            fwd_paths[p, t+1] = f_vae + phi
            z_paths[p, t+1] = z
            short_rates[p, t+1] = (f_vae + phi)[0]
    
    return {
        "z_paths": z_paths,
        "fwd_paths": fwd_paths,
        "short_rates": short_rates,
        "a_est": a_est,
        "z_target": z_target,
    }

# %%
print(f"Running Short Rate AEMM simulation for {ccy_demo}...")
sr_sim = simulate_short_rate_aemm(
    multi_vae, z0, phi, TENORS, vol_z,
    drift_calib, n_steps=252, n_paths=200, seed=42,
)

# %% [markdown]
# ### 7.1 — Compare G2++ vs AEMM

# %%
# Also run classical G2++ for comparison
g2 = G2PlusPlus(a1=0.5, a2=0.05, sigma1=vol_z[0]*np.sqrt(252),
                sigma2=vol_z[1]*np.sqrt(252), rho=-0.3)
f0_market = swap_to_forward(swap_market, TENORS)
g2_fwd, g2_x = g2.simulate(f0_market, TENORS, n_steps=252, n_paths=200)

# %%
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# (a) Short rate fan chart - AEMM
ax = axes[0, 0]
sr = sr_sim["short_rates"] * 100
t_grid = np.arange(sr.shape[1])
ax.fill_between(t_grid, np.percentile(sr, 5, axis=0), np.percentile(sr, 95, axis=0),
                alpha=0.2, color="tab:blue")
ax.fill_between(t_grid, np.percentile(sr, 25, axis=0), np.percentile(sr, 75, axis=0),
                alpha=0.3, color="tab:blue")
ax.plot(t_grid, np.median(sr, axis=0), lw=2, color="tab:blue")
ax.set_title("(a) Short Rate AEMM")
ax.set_ylabel("Short rate (%)")
ax.set_xlabel("Business days")

# (b) Short rate fan chart - G2++
ax = axes[0, 1]
sr_g2 = g2_fwd[:, :, 0] * 100  # first tenor ≈ short rate
ax.fill_between(t_grid, np.percentile(sr_g2, 5, axis=0), np.percentile(sr_g2, 95, axis=0),
                alpha=0.2, color="tab:orange")
ax.fill_between(t_grid, np.percentile(sr_g2, 25, axis=0), np.percentile(sr_g2, 75, axis=0),
                alpha=0.3, color="tab:orange")
ax.plot(t_grid, np.median(sr_g2, axis=0), lw=2, color="tab:orange")
ax.set_title("(b) Classical G(2)++")
ax.set_ylabel("Short rate (%)")
ax.set_xlabel("Business days")

# (c) Terminal curve distribution - AEMM
ax = axes[1, 0]
terminal_aemm = sr_sim["fwd_paths"][:, -1, :] * 100
for i in range(min(50, terminal_aemm.shape[0])):
    ax.plot(TENORS, terminal_aemm[i], alpha=0.15, lw=0.5, color="tab:blue")
ax.plot(TENORS, f0_market * 100, "k-o", lw=2, label="Initial")
ax.set_title("(c) AEMM terminal curves")
ax.set_xlabel("Maturity (years)")
ax.set_ylabel("Forward rate (%)")
ax.legend()

# (d) Terminal curve distribution - G2++
ax = axes[1, 1]
terminal_g2 = g2_fwd[:, -1, :] * 100
for i in range(min(50, terminal_g2.shape[0])):
    ax.plot(TENORS, terminal_g2[i], alpha=0.15, lw=0.5, color="tab:orange")
ax.plot(TENORS, f0_market * 100, "k-o", lw=2, label="Initial")
ax.set_title("(d) G(2)++ terminal curves")
ax.set_xlabel("Maturity (years)")
ax.set_ylabel("Forward rate (%)")
ax.legend()

plt.suptitle(f"Short Rate AEMM vs G(2)++ — {ccy_demo}", fontsize=15, y=1.01)
plt.tight_layout()
plt.savefig("figs/fig_27_sr_aemm_vs_g2.png", dpi=150, bbox_inches="tight")
plt.show()

# %% [markdown]
# ---
# ## 8 — Save results

# %%
q_sr_output = {
    "drift_calibration": drift_calib,
    "phi_shift": phi,
    "simulation_aemm": sr_sim,
    "vol_z": vol_z,
    "z_series": z_series,
}

with open("q_shortrate_aemm.pkl", "wb") as f:
    pickle.dump(q_sr_output, f)

print("Saved to q_shortrate_aemm.pkl")
